name: jojo
services:
  - name: web
    github:
      repo: JUSTSUJAY/JoJo
      branch: main
      deploy_on_push: true
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    run_command: cd backend && gunicorn --bind 0.0.0.0:${PORT:-8080} app:app
    http_port: 8080
    routes:
      - path: /
